package net.ostree.swing;


/*
 * LogOnFrm.java
 *
 * Created on __DATE__, __TIME__
 */


import java.awt.Font;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;


/**
 *
 * @author  __USER__
 */
public class LogOnFrm extends JFrame {

	/** Creates new form LogOnFrm 
	 * @throws Exception */
	public LogOnFrm()  {
				
		//改变系统默认字体
		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		this.setSize(400, 300);
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}
		initComponents();
		// 设置Frame居中显示
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7CFB\u7EDF\u767B\u5F55");
		setResizable(false);
		
		JPanel panel = new JPanel();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(panel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(panel, GroupLayout.PREFERRED_SIZE, 339, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(321, Short.MAX_VALUE))
		);
		panel.setLayout(new GridLayout(0, 1, 0, 0));
				
						jLabel1 = new javax.swing.JLabel();
						panel.add(jLabel1);
						
								jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 24));
								jLabel1.setIcon(new javax.swing.ImageIcon(
										"C:\\Users\\caofeng\\Desktop\\images\\logo.png")); // NOI18N
								jLabel1.setText("\u7CFB\u7EDF\u767B\u5F55");
				jLabel2 = new javax.swing.JLabel();
				panel.add(jLabel2);
				
						jLabel2.setIcon(new javax.swing.ImageIcon(
								"C:\\Users\\caofeng\\Desktop\\images\\userName.png")); // NOI18N
						jLabel2.setText("\u7528\u6237\u540d\uff1a");
				userNameTxt = new javax.swing.JTextField();
				panel.add(userNameTxt);
				jLabel3 = new javax.swing.JLabel();
				panel.add(jLabel3);
				
						jLabel3.setIcon(new javax.swing.ImageIcon(
								"C:\\Users\\caofeng\\Desktop\\images\\password.png")); // NOI18N
						jLabel3.setText("\u5BC6  \u7801\uFF1A");
				passwordTxt = new javax.swing.JPasswordField();
				panel.add(passwordTxt);
				
				label = new JLabel("");
				panel.add(label);
				jb_logon = new javax.swing.JButton();
				panel.add(jb_logon);
				
						jb_logon.setIcon(new javax.swing.ImageIcon(
								"C:\\Users\\caofeng\\Desktop\\images\\login.png")); // NOI18N
						jb_logon.setText("\u767b\u5f55");
						jb_logon.addActionListener(new java.awt.event.ActionListener() {
							public void actionPerformed(java.awt.event.ActionEvent evt) {
								jb_logonActionPerformed(evt);
							}
						});
				jb_reset = new javax.swing.JButton();
				panel.add(jb_reset);
				
						jb_reset.setIcon(new javax.swing.ImageIcon(
								"C:\\Users\\caofeng\\Desktop\\images\\reset.png")); // NOI18N
						jb_reset.setText("\u91cd\u7f6e");
						jb_reset.addActionListener(new java.awt.event.ActionListener() {
							public void actionPerformed(java.awt.event.ActionEvent evt) {
								jb_resetActionPerformed(evt);
							}
						});
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jb_logonActionPerformed(java.awt.event.ActionEvent evt) {
		String userName = userNameTxt.getText();
		String password = new String(passwordTxt.getPassword());
		
		try {
			
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "登录失败");
		}

	}

	private void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {
		this.userNameTxt.setText("");
		this.passwordTxt.setText("");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					//设置此开关量为false即表示关闭之，BeautyEye LNF中默认是true
					BeautyEyeLNFHelper.translucencyAtFrameInactive = false;
					BeautyEyeLNFHelper.launchBeautyEyeLNF();
					//取消设置按钮
					UIManager.put("RootPane.setupButtonVisible", false);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

				new LogOnFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JButton jb_logon;
	private javax.swing.JButton jb_reset;
	private javax.swing.JPasswordField passwordTxt;
	private javax.swing.JTextField userNameTxt;
	private JLabel label;
}